// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODn0zGCemI0mBpjmMnuLgjkZLaUprGL4',
    appId: '1:202755998984:android:1b9566cd8ee24efc2d18bd',
    messagingSenderId: '202755998984',
    projectId: 'flutter-prep-6f19c',
    databaseURL:
        'https://flutter-prep-6f19c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-6f19c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vlZfzAG_dWAmVrVZG_YzvVr6M--Cvp8',
    appId: '1:202755998984:ios:30b5b6ebeaa801e12d18bd',
    messagingSenderId: '202755998984',
    projectId: 'flutter-prep-6f19c',
    databaseURL:
        'https://flutter-prep-6f19c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-6f19c.appspot.com',
    iosBundleId: 'com.example.chatService',
  );
}
